spring.application.name=ecommerce-api

# SERVER
server.port=8081

# POSTGRESQL DATABASE
spring.datasource.url=*****
spring.datasource.username=postgres
spring.datasource.password=*****

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DRIVER
spring.datasource.driver-class-name=org.postgresql.Driver